import Head from 'next/head';
import { StrictMode } from 'react';
import requests from '../requests';
import FirstSection from "./FirstSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StrictMode>
        <FirstSection />
      </StrictMode>
    </div>
  )
}
